package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new slayer.accessibility.service.flutter_accessibility_service.FlutterAccessibilityServicePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_accessibility_service, slayer.accessibility.service.flutter_accessibility_service.FlutterAccessibilityServicePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new flutter.overlay.window.flutter_overlay_window2.FlutterOverlayWindowPlugin2());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_overlay_window2, flutter.overlay.window.flutter_overlay_window2.FlutterOverlayWindowPlugin2", e);
    }
  }
}
